### ISSUE TITLE
Add degree day datasets

### ISSUE THREAD

**Issue by corviday** [pacificclimate/climate-explorer-frontend#172]
There are four gridded degree-day datasets: cooling degree days, freezing degree days, heating degree days, and growing degree days. They are BC-only. Adding them to CE would mean that CE has all the same data plan2adapt has, though the user interfaces are very different.

**Comment by corviday** [comment]
It appears to be failing util.validateLongTermAverageData(), but the backend data looks good to me:
```json
{
  "r3i1p1": {
    "data": {
      "1985-07-03T00:00:00Z": 1219.3448724100413,
      "2025-07-03T00:00:00Z": 1011.862314040631,
      "2085-07-03T00:00:00Z": 661.3033530163773,
      "2055-07-03T00:00:00Z": 772.2954848428196
    },
    "units": "degree_days",
    "modtime": "2018-09-19T22:13:06Z"
  }
}
```

**Comment by corviday** [comment]
```SQL
SELECT * FROM ce_test.emissions
```

| emission_id | emission_long_name | emission_short_name |
|-------------|--------------------|---------------------|
| 2           |                    | historical,rcp85    |
| 3           |                    | historical, rcp85   |

Looks like I need to clean up the emissions scenarios.

**Comment by corviday** [comment]
- [ ] standardize metadata

- [ ] fix stats table to handle annual-only datasets (#193)

- [ ] fix anomaly graph to handle annual-only datasets (#196)

- [ ] fix long term average graph to handle annual-only datasets (#192 )

**Comment by corviday** [comment]
Given recent discussion about separating data and UI issues, this issue, taken solely as a data issue and ignoring the UI issue of #193, is solved.
